### ISSUE TITLE
Add contributing.md 

### ISSUE THREAD

**Issue by Ayush0431** [fayeazahmed/good-first-issue#2]
adding contributing.md helps to improve this repo😊

**Comment by fayeazahmed** [comment]
I didn't think adding these things would be necessary. Thanks for the suggestion

**Comment by Ayush0431** [comment]
hey @fayeazahmed I will add them don't worry 😊

**Comment by Ayush0431** [comment]
hey @fayeazahmed  made a PR for this issue .
